theme = "catppuccin_macchiato"

[editor.file-picker]
hidden = false

[editor]
line-number = "relative"
auto-pairs = false

[keys.normal]
# Minimal remapping to make vim users to feel home
V = "extend_line"
x = "delete_selection"
X = "delete_char_backward"

