theme = "catppuccin_macchiato"

[editor.file-picker]
hidden = false

[editor]
line-number = "relative"
auto-pairs = false

[keys.normal]

# Vim friendly remappings
V = "extend_line_below"
x = "delete_selection"

# Remap Alt shortcuts that overlap with Aerospace to use CTRL instead
"C-[" = "rotate_selection_contents_backward"
"C-]" = "rotate_selection_contents_forward"
C-j = "join_selections_space"
C-k = "remove_selections"
