theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
auto-pairs = false
trim-trailing-whitespace = true

# Fix clipboard when using through tmux
clipboard-provider = "pasteboard"

[editor.file-picker]
hidden = false

[keys.normal]
# Minimal remapping to make vim users to feel home
V = "extend_line"
x = "delete_selection"
X = "delete_char_backward"

